### ISSUE TITLE
Add populate() like FW/1 and deprecate injectProperties()

### ISSUE THREAD

**Issue by seancorfield** [framework-one/di1#53]
See https://groups.google.com/forum/#!topic/framework-one/q88XghdvQHE

**Comment by sneiland** [comment]
Has there been any further analysis on this?

A potential pitfall I see with the current implementation (if this still stands) is where you are consuming a third party api and are converting the returned data into an object using the injectproperties method.

Take for example a user. I read the user data from the the api. I create a userbean in my code and use injectproperties to populate it and all is well. Some time later the third party adds a new datapoint to the user endpoint. Even though I am not using this new datapoint my code now breaks not because a required datapoint is missing, but because a new datapoint is available but not used.

Now I could of course just add onMissingMethod(){} to the bean code but that feels like a hack to handle something that injectProperties should imho do as par for the course, and defining a properties struct argument feels like duplication of effort when I have already defined in the userbean code what properties it has.

**Comment by seancorfield** [comment]
Agreed on the pitfall -- that's why FW/1's `populate()` is safer than DI/1's `injectProperties()` and why this ticket exists. At this point, I still don't know the right solution that doesn't create an even bigger mess.

My gut is still to push people toward FW/1's `populate()` and discourage use of DI/1's `injectProperties()` although I understand the desire to have services that are tied to DI/1 without being tied to FW/1.

My approach would be to have the service return the bean and data to the controller, have the controller `populate()` the bean with the data, and then pass the bean into another service to persist it... or simply call `userbean.save()` if that API is exposed.

That has the benefit of making the service more testable, since it's calling the 3rd party API and returning the data so you've separated concerns more clearly.
